name: my-first-gh-workflow  # workflow name
on:
  schedule: 
  - cron: '*/5 * * * *'
  workflow_dispatch:
    
env:
  COMPANY: Otomato
jobs:                       # list of jobs
  say-hello:             #job name
    runs-on: ubuntu-latest
    env:
      SUBJECT: GithubActions
    steps:                  #list of steps
      - name: Say hello
        run: echo "Hello ${NAME}. Today we're learning ${SUBJECT} with ${COMPANY}."
        env: 
          NAME: Octocat
      - name: Check out code
  special:
  runs-on: ubuntu-latest
  if: contains(env.GITHUB_REF, 'feature')
  steps:
    - name: echo ref
      run: echo $GITHUB_REF
    - 
        uses: actions/checkout@v2
      - name: Show current directory
        run: pwd #where are we?
      - run: ls -la #let's look around
        name: Look around
